/**
 * Interface representing the structure of a Student record in the database.
 */
export interface IStudent {
    s_id: number;
    s_name: string;
    s_course: string;
    course_fee: number;
}

/**
 * Interface representing the data required to create a new Student.
 * 's_id' is omitted as it's typically auto-generated by the database.
 */
export interface ICreateStudent {
    s_name: string;
    s_course: string;
    course_fee: number;
}

/**
 * Interface representing the data that can be updated for an existing Student.
 * All fields are optional, allowing partial updates.
 */
export interface IUpdateStudent {
    s_name?: string;
    s_course?: string;
    course_fee?: number;
}